### ISSUE TITLE
使用多租户给用户授权接口后。调用相应的接口403。初步排查为在授权用户权限接口中赋予了GrantedPermission表TenantId值（不再为null）导致判断该用户是否有相应接口时出错

### ISSUE THREAD

**Issue by vince0823** [Winches/Fabricdot.Core#1]
![1110ADD7-B814-4f57-ABB3-37581D01F5CC](https://user-images.githubusercontent.com/51349340/229401250-3e8e1ef0-0f64-4f0c-b4f1-8f4dc633d9cf.png)
![09AA35BB-06DC-4b45-8693-DFB71E5C5743](https://user-images.githubusercontent.com/51349340/229401251-8123be2b-b0ef-43b5-81ba-a74c3bc1ca4d.png)

**Comment by vince0823** [comment]
而且我在框架源码中找不到PermissionGranting这个项目。

**Comment by Winches** [comment]
`GrantedPermission` is designed for multi-tenancy.The `TenantId` of host user(administrator or whatever) should always be null.You should check tenant data of the request.

**Comment by vince0823** [comment]
我在项目中引入了 multi-tenancy。我创建了一个租户。租户下有两个用户A,B。   A有超级管理员权限。当a给b授予接口权限必然会给GrantedPermission表TenantId赋予a的租户Id。b登录后，调用属于他权限内接口却提示403。我无法判断引起该错误的原因。（还是说GrantedPermission表TenantId的值必须为null吗？不受租户ID的变化。）

**Comment by vince0823** [comment]
![image](https://user-images.githubusercontent.com/51349340/229437986-d9dab4aa-73e8-4f66-99d3-03dea4bc5bc2.png)
是不是因为DbContextBase过滤原因，导致在判断用户接口权限时。无法获取到改用户的租户id 导致的。
![image](https://user-images.githubusercontent.com/51349340/229438442-899ebba6-4058-4128-98a0-091b71282cb0.png)

**Comment by Winches** [comment]
The request must carry the infomation of tenant when 'B' tring to access the protected api.
There are four ways to carry the tenant data in http request:
1. Pass data through query string,like `some/action?__tenant__=abc`.
2. Pass data through route,like `some/{__tenant__}/tenant/action`
3. Pass data through http header.
4. Use the cookie.

**Comment by vince0823** [comment]
![image](https://user-images.githubusercontent.com/51349340/229662266-feb180d9-675b-4e85-ab35-14542eb48678.png)
我尝试了1.2.3种方法都没有成功。tenant data的设置就是如图中设置TenantId的 值吗？

**Comment by vince0823** [comment]
![image](https://user-images.githubusercontent.com/51349340/229664074-c9189ffe-e5ab-4c41-8610-b21f5a5c0f8d.png)

**Comment by Winches** [comment]
You use the wrong name of tenant id.The token name is `__tenant__`.

**Comment by vince0823** [comment]
![image](https://user-images.githubusercontent.com/51349340/229743755-2a0d8509-d7b5-4b5a-bcdf-5d1563eeba5d.png)
![image](https://user-images.githubusercontent.com/51349340/229743933-1685f733-6cc8-4f99-a2d6-7ad3675b88aa.png)
It's Still not working!

**Comment by Winches** [comment]
Please provide a sample project to show your problem.

**Comment by vince0823** [comment]
https://github.com/vince0823/Student.Achieve

**Comment by vince0823** [comment]
[dbo.zip](https://github.com/Winches/Fabricdot.Core/files/11146903/dbo.zip)
This is my local sqlFile.  
username:vince  password:Sw0823!   username :zhangsan  password:Zs0823!   username :lisi  password :Ls0823!

**Comment by Winches** [comment]
You use the wrong order of the middleware.

![image](https://user-images.githubusercontent.com/7054776/229824781-21f81e1e-3ba4-410f-ad06-b0615604afc8.png)

The `UseMultiTenancy` should be ahead of `UseAuthorization`.
```c#
    app.UseMultiTenancy();
    app.UseAuthentication();
    app.UseAuthorization();
```
