### ISSUE TITLE
There is no available unit-of-work

### ISSUE THREAD

**Issue by gkdz-hzx** [Winches/Fabricdot.Core#2]
![image](https://github.com/Winches/Fabricdot.Core/assets/77313031/d06390c4-ddce-4be0-8714-7ffd82a50a21)
当我启动项目时 会报这个错误。

**Comment by Winches** [comment]
Please provide your  module file of entrypoint.

**Comment by gkdz-hzx** [comment]
使用迁移命令生成表后，需重启电脑或者手动运行Debug\net6.0下的exe应用程序，可以启动项目，vs里无法直接启动，应该是vs的原因
